### ISSUE TITLE
Cant download.

### ISSUE THREAD

**Issue by trackc** [Sorrow446/Nugs-DL#8]
It fench the record and creates the directory but it crashes.

Traceback (most recent call last):
  File "./Nugs-DL.py", line 196, in <module>
    main(quality)
  File "./Nugs-DL.py", line 174, in main
    fetchTrack(fetchTrackUrl(item["trackID"], x), item["songTitle"], i, trackTotal, fExt, x)
  File "./Nugs-DL.py", line 95, in fetchTrack
    urllib.request.urlretrieve(trackUrl, f"{trackNum}{fExt}", wrap(trackTitle, trackNum, trackTotal, x))
  File "/usr/lib/python3.6/urllib/request.py", line 246, in urlretrieve
    url_type, path = splittype(url)
  File "/usr/lib/python3.6/urllib/parse.py", line 954, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object

**Comment by trackc** [comment]
The problem was the config file.
